"""Positive-control fixtures for Concur, added after run 2 found Concur said
DO NOT CONCUR in all 21 calls across both prior runs -- it had never once
approved anything, so its divergence rate couldn't be told apart from a
reflexively negative gate that objects regardless of content.

Each `final_decision_fixture` is hand-authored, not live-generated by the
owner-revise step -- the point is to isolate Concur's own behavior from the
noisy propose/contest/revise pipeline that produced ambiguous content before.
Each fixture is built directly from the REAL, QUOTED objections Concur raised
in run 2's transcripts (see `grounded_in`), and explicitly, concretely closes
every one of them. If Concur still says DO NOT CONCUR here, that is strong
evidence its verdict doesn't track content at all. If it says CONCUR, that is
evidence it CAN discriminate when actually satisfied -- the first such
evidence in this PoC.

Same `_brief`/`run_concur_repeats` mechanism as every other Concur check in
this PoC (`lifecycle.py`), reused unmodified: only the input decision text
and the fact that it's hand-authored rather than owner-generated differs.
"""

POSITIVE_CONTROL_SCENARIOS = [
    {
        "slug": "audit-log-retention-positive-control",
        "title": (
            "How long should the platform retain its Decision/Question/Event history (the audit "
            "log) before it can be purged or archived, and where should it be stored?"
        ),
        "context": (
            "This platform's decisions, questions, and events are meant to be the durable, audited "
            "record of engineering choices -- the whole point of making decisions first-class is "
            "having a trustworthy history of what was decided and why. Before implementation, decide "
            "on a retention policy: how long history is kept before it can be purged or archived, "
            "and where it's stored."
        ),
        "concur_role": "Security Reviewer",
        "concur_grounds": "whether this retention approach meets security, audit, and compliance requirements",
        "grounded_in": (
            "runs/audit-log-retention.md (run 2), Security Reviewer's 3 DO NOT CONCUR verdicts: "
            "'does not specify how access... will be controlled and audited', 'does not address how "
            "the integrity and confidentiality of the archived data will be maintained... blast "
            "radius', 'may not meet all regulatory compliance requirements, as some industries "
            "mandate longer retention periods', 'does not explicitly address security controls... "
            "such as encryption at rest and in transit, access controls, and monitoring'."
        ),
        "final_decision_fixture": (
            "Final decision: Retain the Decision/Question/Event history for seven years in a tiered "
            "storage strategy (recent data in high-performance storage, older data moved to "
            "cost-effective archival storage), addressing every raised concern as follows.\n\n"
            "Access control and audit trail: Access to the audit log -- at every tier -- is "
            "restricted via role-based access control to three named roles (Security Reviewer, "
            "Release Manager, and an auditor role), enforced at the storage layer with no "
            "exceptions. Every read and write access is itself logged to a separate, append-only "
            "access log, retained for the same period, and reviewed quarterly by the Security "
            "Reviewer.\n\n"
            "Encryption and integrity: All data is encrypted at rest with AES-256 and in transit "
            "with TLS 1.3. The archival tier uses object-lock/write-once-read-many (WORM) storage "
            "so no role, including administrators, can modify or delete a record before its "
            "retention period expires -- directly limiting the blast radius of any single "
            "compromised credential to read-only exposure, never tampering.\n\n"
            "Regulatory compliance: Legal and Compliance completed a jurisdiction-by-jurisdiction "
            "review against GDPR, SOC 2, and the specific regulations of every industry this "
            "platform currently serves; the seven-year period was confirmed as meeting or exceeding "
            "every applicable minimum. Any future customer whose contract requires a longer period "
            "is handled via a documented per-customer retention override, reviewed by Compliance "
            "before onboarding.\n\n"
            "Monitoring: All access-control and integrity events feed into the platform's existing "
            "monitoring, with alerting configured for any anomalous access pattern (e.g. bulk "
            "export, access outside the three named roles)."
        ),
    },
    {
        "slug": "llm-inference-hosting-positive-control",
        "title": (
            "Should the platform run agent inference against a third-party hosted LLM API, or a "
            "self-hosted model on infrastructure the team operates?"
        ),
        "context": (
            "Every agent role (Architect, Backend Developer, Security Reviewer, etc.) needs an LLM "
            "backing it. Decide, for the pilot phase, whether that's a third-party hosted API "
            "(e.g. a commercial provider) or a self-hosted model on infrastructure the team runs and "
            "operates directly."
        ),
        "concur_role": "Release Manager",
        "concur_grounds": "whether this hosting approach is safe to deploy and roll back in production",
        "grounded_in": (
            "runs/llm-inference-hosting.md (run 1), Release Manager's 3 DO NOT CONCUR verdicts: "
            "'lacks a clear and tested rollback strategy', 'plan to switch to a self-hosted model as "
            "a fallback is not detailed enough to ensure a smooth and safe rollback process', 'does "
            "not ensure that the self-hosted model can be quickly and safely deployed', 'lacks "
            "details on how to manage data consistency and state during a switch', 'needs more "
            "detail on how seamless the switch will be and what the operational implications are'."
        ),
        "final_decision_fixture": (
            "Final decision: Use a third-party hosted LLM API for the pilot phase, with a tested "
            "hybrid fallback to a self-hosted model, addressing every raised concern as follows.\n\n"
            "Rollback strategy and testing: A self-hosted fallback model is kept warm (running, "
            "receiving a small fraction of shadow traffic) at all times, not spun up on demand. "
            "Automatic failover triggers on two independent, pre-defined thresholds (p99 latency "
            "over 2s for 60 consecutive seconds, or error rate over 5% for 30 seconds), verified in "
            "a rehearsed game-day drill that measured full failover completing in under 10 seconds "
            "with zero request loss. Manual rollback is also available via a single documented "
            "runbook command, tested in the same drill.\n\n"
            "State and data consistency during a switch: All agent-role inference calls are "
            "stateless -- no conversation or session state is held by the inference layer itself; "
            "all Decision/Work Item state lives in the platform's own repositories, untouched by "
            "which inference backend served a given call. A switch therefore carries zero risk of "
            "state loss or inconsistency; in-flight requests at the moment of switchover are "
            "retried against the new backend with the same input, not resumed mid-stream.\n\n"
            "Operational implications: On-call is paged automatically on any failover event "
            "(automatic or manual), and the warm self-hosted fallback's capacity is provisioned for "
            "100% of pilot-phase peak load, not a fraction -- verified in the same drill under "
            "synthetic peak-load traffic."
        ),
    },
    {
        "slug": "api-rate-limiting-policy-positive-control",
        "title": (
            "Should the platform enforce API rate limits per-agent-role at a central gateway layer, "
            "or leave rate limiting to each downstream service to implement independently?"
        ),
        "context": (
            "Each agent role (Architect, Backend Developer, Security Reviewer, etc.) calls the "
            "platform's APIs at its own pace. Decide where rate limiting is enforced: a single "
            "centralized gateway that all requests pass through, or independent rate limiting "
            "implemented separately within each downstream service."
        ),
        "concur_role": "Security Reviewer",
        "concur_grounds": (
            "whether this rate-limiting approach adequately protects against abuse or a compromised "
            "agent role, and fails safe rather than open during a gateway rollback or outage"
        ),
        "grounded_in": (
            "runs/api-rate-limiting-policy.md (run 2), Security Reviewer's 2 DO NOT CONCUR verdicts "
            "quoted directly: 'does not specify how rate limits will be enforced or adjusted based "
            "on role or behavior', 'does not clearly outline how the gateway will fail safe during a "
            "rollback or outage', 'does not ensure that the system fails safe during a gateway "
            "rollback or outage', 'does not discuss how rate limits will be adjusted or audited, "
            "which could lead to compliance exposure', 'does not adequately address the blast radius "
            "of compromise, as a compromised gateway could potentially affect all downstream "
            "services'."
        ),
        "final_decision_fixture": (
            "Final decision: Enforce API rate limits at a central gateway layer, addressing every "
            "raised concern as follows.\n\n"
            "Per-role enforcement and abuse detection: Rate limits are configured per agent role "
            "individually (not a single global limit), with tighter limits on roles that don't need "
            "high call volume. Behavioral anomaly detection flags and automatically tightens limits "
            "on any role whose call pattern deviates from its historical baseline (e.g. a "
            "compromised Security Reviewer credential suddenly issuing Architect-role-typical "
            "volume), independent of the static per-role limit.\n\n"
            "Fail-safe on rollback or outage: The gateway is configured fail-closed, not fail-open: "
            "if the gateway itself is unreachable or mid-rollback, downstream services reject all "
            "requests by default rather than allowing unlimited unmetered traffic through. This is "
            "enforced by each downstream service's own minimal local rate limiter, which activates "
            "only as a fallback during a gateway outage -- a deliberate, tested exception to the "
            "\"no per-service logic\" principle, specifically to avoid the fail-open blast-radius "
            "risk.\n\n"
            "Audit and compliance: Every rate-limit adjustment (automatic or manual) is logged with "
            "the role, old limit, new limit, and reason, retained and reviewed by the Security "
            "Reviewer monthly.\n\n"
            "Blast radius: Because rate limits are enforced per-role rather than globally, a single "
            "compromised role is capped at its own limit even if the gateway is otherwise healthy -- "
            "a compromise of one role's credentials cannot exhaust capacity for other roles or bring "
            "down the gateway for everyone."
        ),
    },
]
